# Generated by Django 6.0.3 on 2026-05-03 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
