# Generated by Django 6.0.4 on 2026-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hostel_created_at_hostel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
