# Generated by Django 6.0.4 on 2026-05-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_hostel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.IntegerField(default=70)),
                ('electricity', models.IntegerField(default=60)),
                ('security', models.IntegerField(default=85)),
                ('internet', models.IntegerField(default=75)),
                ('cleanliness', models.IntegerField(default=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
