# Generated by Django 6.0.4 on 2026-05-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hostelanalytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelanalytics',
            name='internet',
        ),
    ]
