# Generated by Django 6.0.4 on 2026-05-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_hostelanalytics_internet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelanalytics',
            name='cleanliness',
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='maintenance',
            field=models.IntegerField(default=40),
        ),
    ]
