# Generated by Django 6.0.4 on 2026-05-09 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_hostelanalytics_cleanliness_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelanalytics',
            options={'verbose_name': 'Hostel Analytics', 'verbose_name_plural': 'Hostel Analytics'},
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostelanalytics',
            name='electricity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hostelanalytics',
            name='water',
            field=models.IntegerField(default=40),
        ),
    ]
