# Generated by Django 6.0.4 on 2026-05-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_hostelanalytics_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelanalytics',
            name='security',
        ),
    ]
