# Generated by Django 6.0.3 on 2026-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_hostelanalytics_security'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelanalytics',
            options={},
        ),
        migrations.RemoveField(
            model_name='hostelanalytics',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hostelanalytics',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='available',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='fri',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='mon',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='occupied',
            field=models.IntegerField(default=65),
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='sat',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='sun',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='thu',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='tue',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='wed',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='hostelanalytics',
            name='electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostelanalytics',
            name='maintenance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostelanalytics',
            name='water',
            field=models.IntegerField(default=0),
        ),
    ]
