# Generated by Django 6.0.3 on 2026-05-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_hostelanalytics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelanalytics',
            options={'verbose_name': 'Hostel Analytics', 'verbose_name_plural': 'Hostel Analytics'},
        ),
    ]
