# Generated by Django 6.0.4 on 2026-05-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_hostelanalytics_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(default='Hostel', max_length=100),
        ),
    ]
