# Generated by Django 6.0.4 on 2026-05-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_hostel_hostel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(default='Boys Lodge', max_length=100),
        ),
    ]
