# Generated by Django 6.0.4 on 2026-05-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_hostel_hostel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('Boys Lodge', 'Boys Lodge'), ('Girls Lodge', 'Girls Lodge'), ('Mixed Hostel', 'Mixed Hostel'), ('Self Contain', 'Self Contain'), ('Single Room', 'Single Room'), ('Shared Apartment', 'Shared Apartment')], default='Boys Lodge', max_length=100),
        ),
    ]
