# Generated by Django 6.0.4 on 2026-05-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_maleroom_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='female_rooms/')),
            ],
        ),
    ]
