# Generated by Django 6.0.4 on 2026-05-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_roombooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomBooking',
        ),
    ]
