# Generated by Django 6.0.4 on 2026-05-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_profile_department_profile_gender_profile_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='malebooking',
            name='emergency_phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
