# Generated by Django 6.0.4 on 2026-05-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_malebooking_emergency_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malebooking',
            name='payment_deadline',
            field=models.DateTimeField(),
        ),
    ]
