# Generated by Django 6.0.4 on 2026-05-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_malebooking_payment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femalebooking',
            name='payment_deadline',
            field=models.DateTimeField(),
        ),
    ]
