# Generated by Django 6.0.4 on 2026-05-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_femalebooking_payment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='femalebooking',
            name='emergency_phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
