# Generated by Django 6.0.4 on 2026-05-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_femalebooking_emergency_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femalebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='malebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
