# Generated by Django 6.0.4 on 2026-06-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_externalbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalbooking',
            name='hostel',
        ),
        migrations.CreateModel(
            name='ExternalRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(default='Single Room', max_length=100)),
                ('capacity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.hostel')),
            ],
        ),
        migrations.AddField(
            model_name='externalbooking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.externalroom'),
            preserve_default=False,
        ),
    ]
