# Generated by Django 6.0.4 on 2026-06-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_externalbooking_hostel_externalroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalroom',
            name='capacity',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='externalroom',
            name='room_type',
            field=models.CharField(default='Shared Room', max_length=100),
        ),
    ]
