# Generated by Django 6.0.4 on 2026-06-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_externalroom_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalbooking',
            name='duration',
            field=models.CharField(choices=[('1 Semester', '1 Semester'), ('1 Academic Session', '1 Academic Session'), ('2 Academic Sessions', '2 Academic Sessions')], default='1 Academic Session', max_length=50),
        ),
        migrations.AddField(
            model_name='externalbooking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalbooking',
            name='emergency_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalbooking',
            name='gender',
            field=models.CharField(default='male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalbooking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
