# Generated by Django 6.0.4 on 2026-06-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_externalbooking_duration_externalbooking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalbooking',
            name='duration',
            field=models.CharField(default='1 Academic Session', max_length=50),
        ),
    ]
