# Generated by Django 6.0.4 on 2026-06-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_externalbooking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalbooking',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='externalbooking',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='externalbooking',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalbooking',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
