# Generated by Django 6.0.4 on 2026-06-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_externalbooking_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalbooking',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hostel'),
        ),
    ]
