# Generated by Django 6.0.4 on 2026-06-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_booking_deadline', models.IntegerField(default=30)),
                ('female_booking_deadline', models.IntegerField(default=30)),
                ('external_booking_deadline', models.IntegerField(default=60)),
                ('allow_male_booking', models.BooleanField(default=True)),
                ('allow_female_booking', models.BooleanField(default=True)),
                ('allow_external_booking', models.BooleanField(default=True)),
            ],
        ),
    ]
