# Generated by Django 6.0.4 on 2026-06-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalbooking',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='femalebooking',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='malebooking',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='femalebooking',
            name='duration',
            field=models.CharField(default='2 yars', max_length=50),
        ),
    ]
