# Generated by Django 6.0.4 on 2026-06-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_externalbooking_booking_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
