# Generated by Django 6.0.4 on 2026-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_systemsettings_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='female_hostel_price',
            field=models.DecimalField(decimal_places=2, default=150000, max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='male_hostel_price',
            field=models.DecimalField(decimal_places=2, default=150000, max_digits=10),
        ),
    ]
