# Generated by Django 6.0.4 on 2026-06-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_systemsettings_female_hostel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaleroom',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='femaleroom',
            name='occupied_beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maleroom',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='maleroom',
            name='occupied_beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='femaleroom',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('filling', 'Filling'), ('full', 'Full')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='maleroom',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('filling', 'Filling'), ('full', 'Full')], default='available', max_length=20),
        ),
    ]
