# Generated by Django 6.0.4 on 2026-06-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_femaleroom_capacity_femaleroom_occupied_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of occupants'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='femalebooking',
            name='duration',
            field=models.CharField(default='2 years', max_length=50),
        ),
        migrations.AlterField(
            model_name='malebooking',
            name='duration',
            field=models.CharField(default='2 years', max_length=50),
        ),
    ]
