# Generated by Django 6.0.4 on 2026-06-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_hostel_capacity_hostel_total_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='total_rooms',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
