# Generated by Django 6.0.4 on 2026-07-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_hostel_total_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalroom',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='externalroom',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='externalroom',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='externalroom',
            name='room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='externalroom',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='externalroom',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
