from django.urls import path
from . import views
from .views import add_hostel
urlpatterns = [
    path('', views.dashboard_home, name='dashboard_home'),
    path('bookings/', views.bookings, name='bookings'),
    path('update-booking/<int:id>/', views.update_booking),
    path('users/', views.users, name='users'),
    path('add-user/', views.add_user),
    path('delete-user/<int:user_id>/', views.delete_user),
    path('upload-image/<int:user_id>/', views.upload_image),
    path('get-user/<int:user_id>/', views.get_user),
    path('search-users/', views.search_users),
    path('export-users/', views.export_users, name='export_users'),
    path("groups/", views.groups_page, name="groups"),
    path("create-group/", views.create_group, name="create_group"),
    path("group/<int:group_id>/users/", views.group_users, name="group_users"),
    path("get-group-users/<int:group_id>/", views.get_group_users),
    path("no-access/", views.no_access, name="no_access"),
    path("group-data/<int:group_id>/", views.get_group_data),
    path("update-group-user/", views.update_group_user),
    path("toggle-permission/", views.toggle_permission),
    path("delete-group/<int:group_id>/", views.delete_group),
    path("update-profile/", views.update_profile, name="update_profile"),
    path("upload-image/", views.upload_image, name="upload_image"),
    path('edit-hostel/<int:id>/',views.edit_hostel,name='edit_hostel'),
    path('delete-hostel/<int:id>/',views.delete_hostel,name='delete_hostel'),
    path('add-hostel/', add_hostel, name='add_hostel'),
    path('analytics/',views.analytics_dashboard,name='analytics_dashboard'),
    path("admin-login/", views.admin_login, name="admin_login"),
    path('files/', views.file_manager, name='file_manager'),
    path('upload-file/', views.upload_file),
    path('get-files/', views.get_files),
    path('delete-file/<int:id>/', views.delete_file),
    path('create-folder/',views.create_folder,name='create_folder'),
    path('delete-folder/<int:id>/',views.delete_folder,name='delete_folder'),
    path( 'rename-file/<int:id>/',views.rename_file,name='rename_file'),
    path('rename-folder/<int:id>/',views.rename_folder,name='rename_folder'),
    path("update-user-status/",views.update_user_status,name="update_user_status"),
    path("room-management/",views.room_management,name="room_management"),
    path("update-room-status/",views.update_room_status,name="update_room_status"),
    path("student/messages/",views.student_messages,name="student_messages"),
    path("admin/messages/<int:user_id>/",views.admin_messages,name="admin_messages"),
    path("admin/chat-list/",views.admin_chat_list,name="admin_chat_list"),
    path("delete-message/<int:message_id>/",views.delete_message,name="delete_message"),
    path("external-booking/<int:room_id>/",views.external_hostel_booking,name="external_hostel_booking"),
    path("update-booking/<int:id>/",views.update_booking,name="update_booking"),
    path("settings/",views.system_settings_page,name="system_settings"),
    path("get-settings/",views.get_system_settings,name="get_settings"),
    path("update-settings/", views.update_system_settings, name="update_settings"),
    path("student-dashboard-data/",views.student_dashboard_data, name="student_dashboard_data"),
    path("search-hostels/",views.search_hostels,name="search_hostels"),
    

]
