# Generated by Django 6.0.3 on 2026-04-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_manage_bookings', 'Can manage bookings'), ('can_view_users', 'Can view users'), ('can_delete_users', 'Can delete users')],
            },
        ),
    ]
