# Generated by Django 6.0.4 on 2026-05-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_fileitem_user_folder_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
